// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// createBackground
NumericVector createBackground(NumericVector m1, NumericVector m2, NumericVector m3, IntegerVector d);
RcppExport SEXP trackdem_createBackground(SEXP m1SEXP, SEXP m2SEXP, SEXP m3SEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type m1(m1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type m2(m2SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type m3(m3SEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type d(dSEXP);
    __result = Rcpp::wrap(createBackground(m1, m2, m3, d));
    return __result;
END_RCPP
}
// getCoords
NumericVector getCoords(NumericVector m, IntegerVector d);
RcppExport SEXP trackdem_getCoords(SEXP mSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type m(mSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type d(dSEXP);
    __result = Rcpp::wrap(getCoords(m, d));
    return __result;
END_RCPP
}
// subtractBackground
NumericVector subtractBackground(NumericVector m1, NumericVector bg, IntegerVector d);
RcppExport SEXP trackdem_subtractBackground(SEXP m1SEXP, SEXP bgSEXP, SEXP dSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type m1(m1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type bg(bgSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type d(dSEXP);
    __result = Rcpp::wrap(subtractBackground(m1, bg, d));
    return __result;
END_RCPP
}
