# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Background detection
#'
#' \code{createBackground} is a function to create a still background,
#' exluding movies objects, using loaded image sequences as input, taking
#' mean pixel values over all frames.
#' @param allFullImages Array containing all images (and three color layers)
#' @author Marjolein Bruijning & Marco D. Visser
#' @examples
#' \dontrun{
#' stillBack <- createBackground (allFullImages)
#'	}
#' @return Returns array with still background.
#' @export
createBackground <- function(m1, m2, m3, d) {
    .Call('trackdem_createBackground', PACKAGE = 'trackdem', m1, m2, m3, d)
}

#' Get coordinates of all particles
#'
#' \code{getCoords} finds all coordinates of values  > 1 in a matrix
#' @param m bla
#' @author Marjolein Bruijning & Marco D. Visser
#' @return Returns array with still background.
#' @export
getCoords <- function(m, d) {
    .Call('trackdem_getCoords', PACKAGE = 'trackdem', m, d)
}

#' Background subtraction
#'
#' \code{subtractBackground} is a function to subtract each
#' image from the created still background.
#' The objects created through the function contain all moving
#' pixels.
#' @param background Array containing still background.
#' @param images Array containing all images.
#' @author Marjolein Bruijning & Marco D. Visser
#' @examples
#' \dontrun{
#'
#'   allImages <- subtractBackground(background=stillBack,allFullImages)
#'	}
#' @seealso \code{\link{createBackground}}
#' @return Returns array with same size as images, subtracted from background.
#' @concept What is the broad searchable concept?
#' @export
subtractBackground <- function(m1, bg, d) {
    .Call('trackdem_subtractBackground', PACKAGE = 'trackdem', m1, bg, d)
}

