# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
cb <- function(m1, m2, m3, d) {
    .Call('trackdem_cb', PACKAGE = 'trackdem', m1, m2, m3, d)
}

#' Get coordinates of all particles
#'
#' \code{getCoords} finds all coordinates of values  > 0 in a matrix
#' @param m Matrix containing values 0's and values > 0.
#' @param d Vector containing dimension of matrix.
#' @author Marjolein Bruijning & Marco D. Visser
#' @return Returns matrix with x and y coordinates for all labels > 0.
#' @export
getCoords <- function(m, d) {
    .Call('trackdem_getCoords', PACKAGE = 'trackdem', m, d)
}

#' @export
sb <- function(m1, bg, d) {
    .Call('trackdem_sb', PACKAGE = 'trackdem', m1, bg, d)
}

